name: C++ ASCII85 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ make cmake libgtest-dev

    - name: Build GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake -S . -B build
        sudo cmake --build build
        sudo cp build/lib/*.a /usr/lib

    - name: Build project
      run: make

    - name: Run unit tests
      run: make test
